### ISSUE TITLE
Multiple expects in the same step_definition 

### ISSUE THREAD

**Issue by aluzardo** [aluzardo/protractor-cucumber-tests#4]
**Description:** If in one step you add more than one expect only the first expect using notify it is the one that the test is checking.

For example if you change this code https://github.com/aluzardo/protractor-cucumber-tests/blob/master/features/step_definitions/calculator.step.js#L36 for that other code:

```
this.Then(/^The last and the fist operation should match$/, function (next) {
        calculatorPage.add(1, 2);
        calculatorPage.add(3, 4);

        var history = calculatorPage.getHistory();
        this.expect(history.last().getText()).to.eventually.contains('1 + 2').and.notify(next);
        this.expect(history.first().getText()).to.eventually.contains('Wrong numbers').and.notify(next);

    });
```

The result should be **Fail** but it is **Successful**

**Comment by aluzardo** [comment]
Trying to fix with @flashquartermaster help.  https://github.com/flashquartermaster/myappname/issues/1

**Comment by flashquartermaster** [comment]
@aluzardo Hi, I have had a look at the project and it is running ok for me. I only made the following changes:

I added a file env.js to the features/support directory containing the following:

```
var configure = function () {
    this.setDefaultTimeout(20 * 1000);
};

module.exports = configure;
```

That sorted out your timeouts issue.

I then altered your package.json to run the local version of protractor. I believe it is not great to rely on global dependancies for this kind of testing, I have had problems with missing modules even when there is an npm link in the node_modules directory:

```
"scripts": {
...
    "test-desktop": "node_modules/.bin/protractor conf.js",
...
  },
```

Then if I did:

```
this.expect(history.last().getText()).to.eventually.contains('1 + 3');
this.expect(history.first().getText()).to.eventually.contains('3 + 4').and.notify(next);
```

I got:

```
E/launcher - AssertionError: expected '2:46:07 PM 1 + 2 3' to include '1 + 3'
```

And if I did:

```
this.expect(history.last().getText()).to.eventually.contains('1 + 2');
this.expect(history.first().getText()).to.eventually.contains('3 + 5').and.notify(next);
```

I got:

```
Failures:

1) Scenario: The calculator history should work properly - features/list-elements.feature:7
   Step: And The last and the fist operation should match - features/list-elements.feature:10
   Step Definition: features/step_definitions/calculator.step.js:31
   Message:
     AssertionError: expected '2:47:23 PM 3 + 4 7' to include '3 + 5'

1 scenario (1 failed)
3 steps (1 failed, 2 passed)
```

Do you want to give it a try?

**Comment by flashquartermaster** [comment]
@aluzardo Just out of interest I noticed that in your original bug you were doing:

```
this.expect(history.last().getText()).to.eventually.contains('1 + 2').and.notify(next);
this.expect(history.first().getText()).to.eventually.contains('Wrong numbers').and.notify(next);
```

Under these circumstances the first expect will evaluate to true and then calls back to next() so the second expectation will never be reached and evaluated because you have already called back from the function.

**Comment by aluzardo** [comment]
Thanks a los @flashquartermaster for the code review. 

As you said in the second comment, I fixed the bug because I was sending the notification in the two expects and only the first one was evaluated.

I fixed that bug only sending the notification in the last expect. The problem is that if the first expect fail as you mention in the first comment. 

I got:

```
E/launcher - AssertionError: expected '2:46:07 PM 1 + 2 3' to include '1 + 3'
```

But for some reason this is not a Failure it is a crash in the code. All the tests stop and show the error but I can't get a final report similar than than this:

```
Failures:

1) Scenario: The calculator history should work properly - features/list-elements.feature:7
   Step: And The last and the fist operation should match - features/list-elements.feature:10
   Step Definition: features/step_definitions/calculator.step.js:31
   Message:
     AssertionError: expected '2:47:23 PM 3 + 4 7' to include '3 + 5'

1 scenario (1 failed)
3 steps (1 failed, 2 passed)
```

I noticed that only the expects with `.and.notify(next);` are well handled but other are simply a error and stop the test if it is not successful.

**Comment by flashquartermaster** [comment]
@aluzardo Ah, ok you want to get rid of the cash error. Try this:

~~~
var scope = this;
this.expect( history.last().getText() ).to.eventually.contains( '1 + 2' )
.then( function(result){
    scope.expect( history.first().getText() ).to.eventually.contains( '3 + 4' ).and.notify(next);
},function(error){
    scope.notify( next( new Error(error) ) );
});
~~~

Now if your first assertion fails you wont get the crash and if your second assertion fails you will get a standard failure

**Comment by flashquartermaster** [comment]
@aluzardo Ah, ok you want to get rid of the crash problem. Try this:

```
var scope = this;
this.expect( history.last().getText() ).to.eventually.contains( '1 + 2' )
.then( function( result ){
    scope.expect( history.first().getText() ).to.eventually.contains( '3 + 4' ).and.notify(next);
},function( error ){
    scope.notify( next( error ) );
});
```

Now you should get a standard failure if one or other of your assertions fail.

BTW: I have only tested this with 'test-desktop', I tried the same approach in my own project quickly and it did not work on android or iOS the way I am set up.

**Comment by aluzardo** [comment]
Thanks @flashquartermaster it is working fine. You are awesome.

**Comment by flashquartermaster** [comment]
@aluzardo Glad to help.
